import type { LLMProviderConfig } from '@/types/llm';

export const LLM_PROVIDERS: LLMProviderConfig[] = [
  {
    id: 'rork',
    name: 'Rork (Built-in)',
    description: 'Free built-in AI - no API key required',
    icon: '🤖',
    color: '#6366F1',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyPlaceholder: '',
    docsUrl: 'https://rork.com',
    models: ['gpt-4o', 'claude-3.5-sonnet', 'gemini-2.0-flash'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4, GPT-3.5, and more',
    icon: '🟢',
    color: '#10A37F',
    requiresApiKey: true,
    apiKeyLabel: 'OpenAI API Key',
    apiKeyPlaceholder: 'sk-...',
    baseUrl: 'https://api.openai.com/v1',
    docsUrl: 'https://platform.openai.com/api-keys',
    models: ['gpt-4o', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 3 models',
    icon: '🔶',
    color: '#D97757',
    requiresApiKey: true,
    apiKeyLabel: 'Anthropic API Key',
    apiKeyPlaceholder: 'sk-ant-...',
    baseUrl: 'https://api.anthropic.com/v1',
    docsUrl: 'https://console.anthropic.com/settings/keys',
    models: ['claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
  },
  {
    id: 'google',
    name: 'Google AI',
    description: 'Gemini models',
    icon: '✨',
    color: '#4285F4',
    requiresApiKey: true,
    apiKeyLabel: 'Google AI API Key',
    apiKeyPlaceholder: 'AIza...',
    baseUrl: 'https://generativelanguage.googleapis.com/v1',
    docsUrl: 'https://makersuite.google.com/app/apikey',
    models: ['gemini-pro', 'gemini-pro-vision', 'gemini-1.5-pro'],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Access 100+ models through one API',
    icon: '🌐',
    color: '#8B5CF6',
    requiresApiKey: true,
    apiKeyLabel: 'OpenRouter API Key',
    apiKeyPlaceholder: 'sk-or-...',
    baseUrl: 'https://openrouter.ai/api/v1',
    docsUrl: 'https://openrouter.ai/keys',
    models: [
      'openai/gpt-4o',
      'anthropic/claude-3-opus',
      'google/gemini-pro',
      'meta-llama/llama-3-70b-instruct',
      'mistralai/mistral-large',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral and Mixtral models',
    icon: '🌊',
    color: '#FF7000',
    requiresApiKey: true,
    apiKeyLabel: 'Mistral API Key',
    apiKeyPlaceholder: '...',
    baseUrl: 'https://api.mistral.ai/v1',
    docsUrl: 'https://console.mistral.ai/api-keys',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest'],
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast LLM inference',
    icon: '⚡',
    color: '#F55036',
    requiresApiKey: true,
    apiKeyLabel: 'Groq API Key',
    apiKeyPlaceholder: 'gsk_...',
    baseUrl: 'https://api.groq.com/openai/v1',
    docsUrl: 'https://console.groq.com/keys',
    models: ['llama-3.1-70b-versatile', 'mixtral-8x7b-32768', 'gemma-7b-it'],
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Open-source models at scale',
    icon: '🤝',
    color: '#00D4AA',
    requiresApiKey: true,
    apiKeyLabel: 'Together API Key',
    apiKeyPlaceholder: '...',
    baseUrl: 'https://api.together.xyz/v1',
    docsUrl: 'https://api.together.xyz/settings/api-keys',
    models: ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Search-augmented AI models',
    icon: '🔍',
    color: '#20808D',
    requiresApiKey: true,
    apiKeyLabel: 'Perplexity API Key',
    apiKeyPlaceholder: 'pplx-...',
    baseUrl: 'https://api.perplexity.ai',
    docsUrl: 'https://www.perplexity.ai/settings/api',
    models: ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command models for enterprise',
    icon: '🧬',
    color: '#D18EE2',
    requiresApiKey: true,
    apiKeyLabel: 'Cohere API Key',
    apiKeyPlaceholder: '...',
    baseUrl: 'https://api.cohere.ai/v1',
    docsUrl: 'https://dashboard.cohere.com/api-keys',
    models: ['command-r-plus', 'command-r', 'command'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Powerful reasoning models',
    icon: '🧠',
    color: '#6366F1',
    requiresApiKey: true,
    apiKeyLabel: 'DeepSeek API Key',
    apiKeyPlaceholder: 'sk-...',
    baseUrl: 'https://api.deepseek.com/v1',
    docsUrl: 'https://platform.deepseek.com/api_keys',
    models: ['deepseek-chat', 'deepseek-coder'],
  },
  {
    id: 'ollama',
    name: 'Local (Ollama)',
    description: 'Run models locally on your device',
    icon: '🦙',
    color: '#000000',
    requiresApiKey: false,
    apiKeyLabel: 'Ollama Server URL',
    apiKeyPlaceholder: 'http://localhost:11434',
    baseUrl: 'http://localhost:11434',
    docsUrl: 'https://ollama.ai',
    models: [],
  },
  {
    id: 'local',
    name: 'On-Device AI',
    description: 'Download and run models directly on your device',
    icon: '📱',
    color: '#34C759',
    requiresApiKey: false,
    apiKeyLabel: 'No API Key Required',
    apiKeyPlaceholder: '',
    docsUrl: 'https://rork.com/local-ai',
    models: [],
  },
];
