import type { MCPSoServer } from '@/types/mcp';

export const POPULAR_MCP_SERVERS: MCPSoServer[] = [
  {
    name: 'Filesystem',
    description: 'Secure file operations with configurable access controls',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed/files'],
    category: 'File Operations',
    vendor: 'Anthropic',
    icon: '📁',
  },
  {
    name: 'GitHub',
    description: 'Repository management, file operations, and GitHub API integration',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    category: 'Development',
    vendor: 'Anthropic',
    icon: '🐙',
  },
  {
    name: 'Google Drive',
    description: 'File access and search capabilities for Google Drive',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gdrive'],
    category: 'Cloud Storage',
    vendor: 'Anthropic',
    icon: '📊',
  },
  {
    name: 'Brave Search',
    description: 'Web and local search using Brave\'s Search API',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    category: 'Search',
    vendor: 'Anthropic',
    icon: '🔍',
  },
  {
    name: 'PostgreSQL',
    description: 'Read-only database access with schema inspection',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost/mydb'],
    category: 'Database',
    vendor: 'Anthropic',
    icon: '🐘',
  },
  {
    name: 'Puppeteer',
    description: 'Browser automation and web scraping',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    category: 'Web Automation',
    vendor: 'Anthropic',
    icon: '🎭',
  },
  {
    name: 'Slack',
    description: 'Channel management and messaging',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    category: 'Communication',
    vendor: 'Anthropic',
    icon: '💬',
  },
  {
    name: 'Memory',
    description: 'Knowledge graph-based persistent memory system',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    category: 'AI Tools',
    vendor: 'Anthropic',
    icon: '🧠',
  },
  {
    name: 'Fetch',
    description: 'Web content fetching and conversion for efficient LLM usage',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    category: 'Web',
    vendor: 'Anthropic',
    icon: '🌐',
  },
  {
    name: 'Sequential Thinking',
    description: 'Dynamic and reflective problem-solving through thought sequences',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    category: 'AI Tools',
    vendor: 'Anthropic',
    icon: '🤔',
  },
];
